### ISSUE TITLE
Array transformations

### ISSUE THREAD

**Issue by mlee156** [alee156/NeuroCV#1]
This is a super easy question, I'm just confirming to make sure I'm not screwing up

`a = np.random.randint(0,10,(2,2,2))`

If I generate a random 2x2x2 cube with dataset

```
[[[2 6]
 [1 9]]
[[7 9]
 [2 6]]]
```

When I flatten it to produce dataset
`[2 6 1 9 7 9 2 6]`

Is the histogram I'm producing supposed to have 1 one, 2 twos, 2 sixes, 1 seven, 2 nines?

**Comment by jovo** [comment]
yes.
